# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:14.7
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: some_system_user
      POSTGRES_PASSWORD: some_system_password
      POSTGRES_DB: parametrai-db